name: Build Modules
on: 
  workflow_call:
  workflow_dispatch:
  push:
   paths-ignore:
      - '**.md'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Install aapt
        run: |
          sudo apt install aapt jq
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
        
      - name: Build Modules/APKs
        run: |
          chmod +x ./script.sh
          echo "" >version.conf
          ./script.sh
        env:
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
     
